"""Golden-value tests: the Python RNG port must match the TypeScript byte-for-byte.

Goldens were generated by running the exact function bodies from
frontend/src/lib/rng.ts under node (backend/tools/golden_rng.mjs).
"""

from app.rng import hex_n, js_hash, mulberry32


def test_hash():
    # hashes of the seeds the console derives identifiers from
    assert js_hash("NCRP-2026-0918-4471") == 1837259757
    assert js_hash("NCRP-2026-0918-4471#m0") == 1478433231
    assert js_hash("NCRP-2026-0918-4468g") == 2056306868
    # non-ASCII seed (UTF-16 code units, not code points)
    assert js_hash("TKN-test-σ") == 3586902281
    assert js_hash("") == 2166136261
    assert js_hash("OVI3") == 2261383664


def test_mulberry32_sequence():
    g = mulberry32(0)
    seq = [round(g(), 12) for _ in range(6)]
    assert seq == [
        0.266429208685,
        0.000329745701,
        0.223272027448,
        0.146202147938,
        0.467327822931,
        0.545049082721,
    ]
    # a = 0xFFFFFFFF exercises the signed/unsigned boundary
    g2 = mulberry32(4294967295)
    assert round(g2(), 12) == 0.896422614111
    # deterministic across instances
    g3 = mulberry32(42)
    g4 = mulberry32(42)
    assert [g3() for _ in range(20)] == [g4() for _ in range(20)]


def test_hex_n():
    # the first mule token of case 4471 — the exact token the console shows
    assert hex_n("NCRP-2026-0918-4471#m0a", 4) == "53F1"
    assert hex_n("NCRP-2026-0918-4471#m0b", 4) == "C0A0"
    assert hex_n("NCRP-2026-0918-4471blk", 16) == "F7EEB6B5A1BDBD02"
    assert hex_n("NCRP-2026-0918-4471|rep|1758187800000", 20) == "C7F80D068CE59B98B327"
    assert hex_n("", 8) == "5F8FE648"
